### ISSUE TITLE
Lesson13 HomeWork Task3 

### ISSUE THREAD

**Issue by DinamickaDevelopment** [Glebfedchenko/GlebFedchenko_DinamikaDevelopment#5]
1) Нет условия задачи в комментариях
2) Файл app.js не должен быть в папке с библиотеками
3) В поле имени можно вводить цифры
4) Не все поля проверяются
5) Нет подсказок для формата ввода данных.

**Comment by Glebfedchenko** [comment]
1. Added comments to task
2. Removed app.js from libs folder
3. Added regexp conditions to fields
4. All fields are checked now
5. Added hints for user input and message after form submission
